### PR TITLE
Add Banjo's Backpack romhack support, auxiliary framebuffer refactor, and misc fixes

### LINKED ISSUE #14: Used moves not saving to file
Using a move for the first time gives a chime. On save and reload, these chimes continue. Used move flags are not currently saved to file, though the json entries exist.

### PR DESCRIPTION
**Pull request by JeodC**
## Banjo's Backpack
Adds runtime support for Banjo's Backpack romhacks. Torch can detect romhacks created with BB via new ConfigFactory. Assets are based on v1.0 so are easily exported, while code modifications done by BB are exported to a new `aGameConfig` file like `aBKAssetTable` already is. These modifications are documented in the `docs/` folder.

At runtime, romhack o2r files are detected and `aGameConfig` is imported to reconfigure vanilla hardcoded values.

Relevant:
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/191e56e2b512c69276c2ab6a22b18d9844127b42
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/118eb91340a54f68827db087982f04ad9b0916b3

## Torch
Bumps Torch to add the ConfigFactory used by the BB extraction process. Also fixes a race condition between Torch's o2r generation and a running game instance that could cause a crash on first launch.

Relevant:
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/c80d7f0762a4324266b92bc1e8fac159eee3fddf
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/6ac6eab2aa9eaa786ebcc061a3c5145d8480fe94
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/006ae426ed14bb4c5e87a6af304f6f49de11f289

## Bottles Bonus
Fixes persistence of Bottles Bonus completion state across save/load. Renames `gCompletedBottleBonusGames` to match decomp. Bonus puzzle index is now saved and restored correctly, and bonus text is skipped on reload.

Relevant:
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/481ca31a931b31b5db668f7243769edeb8974389
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/7bf31c70e632a18335e084460a12ab32f682b518

## Widescreen HUD
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/ec30bb10b9564cfced6af22a5c048183d04d720d

### Attract Demos
In v1.1 roms and DX11 some crashes were fixed involving attract demos. Draw distance also caused desyncs due to actor updates.

Relevant:
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/5520f272cb10847e778261fa987350d2ff663f4f
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/33879df13be71db9579bec6b96629d129d10d568
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/0d44084003178641de5f6a7c43cefc748b22816c

### Jinjo HUD not working in Release builds due to optimizations
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/c82117d896658a295b1d20e08c91096f595c87f5

### Jiggy Podium Culling
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/058cd3572e7aaf81d49fff5f8fc905da7e451dc1

### Save issues and Enhancements
Previously I had marked the wrong locations/was not as detailed enough in Enhancements. Enhancements were not working properly due to being hooked up in the wrong locations and/or not doing enough to make the enhancement work as expected.

Relevant:
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/738a1cecbbebbfd3e5f47ef5fe4200b102b8f400
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/9512702be5a49d084d06e6b2dd4a948607c5ede7
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/4397dd38452ccca84bbf7ca0be8c05b8cc33c69d
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/77017a64d52e277c935ca06b5987149c3c85a4d7

### LAIR Timer
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/e8229be312df1066e1a15f4fe0330315c38826da

### Audio Thread and HUD Centering
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/aa2fc734dac9acbcda71f8835a2cd5a2521109ee

### Return to Lair Build Fix and va_list Abuse
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/21346e1abb3418b6016d4557d9a3ef5940cb9696

### C-Button to Axis Filtering
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/6330c8df4cece97c9393b3d22d3e39b68f7d3ebe
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/e05e82425bfd673b45a7e40b702de1a4ad7a5b46

### DialogFactory Importer Fix
I had expected to run into this in Furnace Fun, but testing v1.1 revealed this crash during a MMM attract demo.

Relevant:
https://github.com/HarbourMasters/Lighthouse/pull/22/commits/ba07213737a92194b694857401c4843801f6c22b

## Resolves
Closes #14, #15, #16. Adds marker for #18.

### CODE REVIEW

File: src/port/enhancements/events/hooks/list/EngineEvent.h [hunk 1]
```diff
@@ -9,4 +9,4 @@ typedef enum VBehaviorID {
     VB_INIT_RETURN_TO_LAIR,
 } VBehaviorID;
 
-DEFINE_EVENT(VanillaBehavior, VBehaviorID id; bool* should; va_list args;);
+DEFINE_EVENT(VanillaBehavior, VBehaviorID id; bool* should; void* args;);
```
Comment (Malkierian) [inline src/port/enhancements/events/hooks/list/EngineEvent.h:12]: Why?

Comment (JeodC) [reply src/port/enhancements/events/hooks/list/EngineEvent.h:12]: Caused a compile error in clang.

`va_list` can't be safely stored in a struct and reused across multiple listeners — it's undefined behavior. Nothing was actually passing variadic args here, so replaced with `void*` which is simpler and portable--and actually fixed the error.

File: src/MMM/minigame_shed.c [hunk 2]
```diff
@@ -66,7 +66,7 @@ struct {
     Struct_MMM_3D50_0 *unk4;
     u8 unk8;
     BKModel *unkC;
-    s32 unk10;
+    uintptr_t unk10;
```
Comment (Malkierian) [inline src/MMM/minigame_shed.c]: Why the uintptr type when every time it's used it's cast to intptr?

Comment (JeodC) [reply src/MMM/minigame_shed.c]: Oops, sorry. Last thing I did last night and I had just used uintptr_t in skinning.c. Correct, it's redundant here.

**Review by Malkierian — APPROVED** [review]
